spring.application.name=studybase


spring.datasource.url=jdbc:sqlite:study_platform.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Spring MVC Configuration
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Display detailed error messages
server.error.include-stacktrace=always
server.error.include-message=always

# CORS pre JavaFX klienta
spring.web.cors.allowed-origins=http://localhost:8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration